#ifndef PATRIKSHELL_ERRORS_H
#define PATRIKSHELL_ERRORS_H

#define ERROR_CONFIG_FILE_CANT_READ -1
#define ERROR_CONFIG_FILE_MISSING_PARAMS -2
#define ERROR_HISTORY_OPEN_DB -3
#define ERROR_HISTORY_MAP_DB -4
#define ERROR_RUNNER_FORK_FAILED -5

#endif //PATRIKSHELL_ERRORS_H
